# Generated by Django 3.0.6 on 2020-05-07 12:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('call_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='forwarding_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='People who call this lead source will be connected with this phone number. Must include international prefix - e.g. +1 555 555 55555', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='incoming_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='A phone number purchased through Twilio', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(blank=True, help_text='E.g. "Downtown billboard"', max_length=100),
        ),
    ]
